---
collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  - name: geerlingguy.docker
    version: "7.0.2"
  - name: geerlingguy.security
    version: "2.0.1"